# Generated by Django 3.2.16 on 2022-11-24 09:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Berry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('berry', models.CharField(max_length=50, verbose_name='Ягоды')),
                ('price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Цена')),
            ],
        ),
        migrations.CreateModel(
            name='Cake',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='Торт', max_length=200, verbose_name='Название торта')),
                ('price', models.DecimalField(decimal_places=2, default=0, max_digits=20, verbose_name='Цена')),
                ('berry', models.ForeignKey(blank=True, default=0, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='bot_app.berry')),
            ],
            options={
                'verbose_name': 'Торт',
                'verbose_name_plural': 'Торты',
            },
        ),
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='ФИО')),
                ('birthday', models.DateField(null=True, verbose_name='День рождения')),
                ('contact', models.CharField(max_length=200, verbose_name='Телефон')),
                ('address', models.CharField(max_length=200, verbose_name='Адрес')),
            ],
        ),
        migrations.CreateModel(
            name='Courier',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='ФИО')),
                ('contact', models.CharField(max_length=200, verbose_name='Телефон')),
            ],
        ),
        migrations.CreateModel(
            name='Decor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('decor', models.CharField(max_length=50, verbose_name='Декор')),
                ('price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Цена')),
            ],
        ),
        migrations.CreateModel(
            name='Form',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('form', models.CharField(max_length=50, verbose_name='Форма торта')),
                ('price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Цена')),
            ],
        ),
        migrations.CreateModel(
            name='NumberLevel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('level', models.CharField(max_length=50, verbose_name='Уровни')),
                ('price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Цена')),
            ],
        ),
        migrations.CreateModel(
            name='Topping',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('topping', models.CharField(max_length=50, verbose_name='Топпинг')),
                ('price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Цена')),
            ],
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_time', models.DateField(auto_now_add=True, null=True, verbose_name='Дата заказа')),
                ('comment', models.TextField(blank=True, max_length=200, null=True, verbose_name='Комментарий к заказу')),
                ('delivery_address', models.CharField(max_length=200, verbose_name='Адрес доставки')),
                ('delivery_date', models.DateField(verbose_name='Дата доставки')),
                ('delivery_time', models.DateField(verbose_name='Желаемое время доставки')),
                ('total', models.DecimalField(decimal_places=2, default=0, max_digits=20, verbose_name='Всего')),
                ('cake', models.ForeignKey(default='Торт', on_delete=django.db.models.deletion.CASCADE, to='bot_app.cake')),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bot_app.client')),
            ],
        ),
        migrations.CreateModel(
            name='Delivery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('delivery_time', models.DateField(verbose_name='Предполагаемое время доставки')),
                ('courier', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bot_app.courier')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bot_app.order')),
            ],
        ),
        migrations.AddField(
            model_name='cake',
            name='decor',
            field=models.ForeignKey(blank=True, default=0, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='bot_app.decor'),
        ),
        migrations.AddField(
            model_name='cake',
            name='form',
            field=models.ForeignKey(blank=True, default=0, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='bot_app.form'),
        ),
        migrations.AddField(
            model_name='cake',
            name='level',
            field=models.ForeignKey(blank=True, default=0, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='bot_app.numberlevel'),
        ),
        migrations.AddField(
            model_name='cake',
            name='topping',
            field=models.ForeignKey(blank=True, default=0, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='bot_app.topping'),
        ),
    ]
